# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculateBetasAndSE <- function(XX, db_CpG, trait) {
    .Call('_MethParquet_calculateBetasAndSE', PACKAGE = 'MethParquet', XX, db_CpG, trait)
}

solveAndCalculateResiduals <- function(XX, db_CpG) {
    .Call('_MethParquet_solveAndCalculateResiduals', PACKAGE = 'MethParquet', XX, db_CpG)
}

